/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomLevel {
  'id' : bigint,
  'worldWidth' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'authorSession' : string,
  'author' : Principal,
  'platformsJson' : string,
  'bgHue' : bigint,
}
export interface LeaderboardRow {
  'username' : string,
  'bestCompletionTimeMs' : bigint,
  'totalDeaths' : bigint,
  'totalWins' : bigint,
  'bestStage' : bigint,
  'sessionId' : string,
}
export interface UserStats {
  'bestCompletionTimeMs' : bigint,
  'totalDeaths' : bigint,
  'totalWins' : bigint,
  'bestStage' : bigint,
}
export interface _SERVICE {
  'adminResetUsernames' : ActorMethod<[string], undefined>,
  'claimOwnerPrincipal' : ActorMethod<[string], boolean>,
  'deleteLevel' : ActorMethod<[string, bigint], undefined>,
  'deleteMyLevel' : ActorMethod<[string], undefined>,
  'getAllUsernames' : ActorMethod<[], Array<[string, string]>>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardRow>>,
  'getLevelById' : ActorMethod<[bigint], [] | [CustomLevel]>,
  'getMyLevel' : ActorMethod<[string], [] | [CustomLevel]>,
  'getMyLevels' : ActorMethod<[string], Array<CustomLevel>>,
  'getMyStats' : ActorMethod<[string], [] | [UserStats]>,
  'getMyUsername' : ActorMethod<[string], [] | [string]>,
  'getPublicLevels' : ActorMethod<[], Array<CustomLevel>>,
  'getSpeedLeaderboard' : ActorMethod<[], Array<LeaderboardRow>>,
  'registerUsername' : ActorMethod<[string, string], undefined>,
  'resetMyUsername' : ActorMethod<[string], undefined>,
  'saveCustomLevel' : ActorMethod<
    [string, string, string, bigint, bigint],
    undefined
  >,
  'saveGameResult' : ActorMethod<[string, bigint, bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];