/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CustomLevel {
    id: bigint;
    worldWidth: bigint;
    name: string;
    createdAt: bigint;
    authorSession: string;
    author: Principal;
    platformsJson: string;
    bgHue: bigint;
}
export interface UserStats {
    bestCompletionTimeMs: bigint;
    totalDeaths: bigint;
    totalWins: bigint;
    bestStage: bigint;
}
export interface LeaderboardRow {
    username: string;
    bestCompletionTimeMs: bigint;
    totalDeaths: bigint;
    totalWins: bigint;
    bestStage: bigint;
    sessionId: string;
}
export interface backendInterface {
    adminResetUsernames(secret: string): Promise<void>;
    claimOwnerPrincipal(secret: string): Promise<boolean>;
    deleteLevel(sessionId: string, id: bigint): Promise<void>;
    deleteMyLevel(sessionId: string): Promise<void>;
    getAllUsernames(): Promise<Array<[string, string]>>;
    getLeaderboard(): Promise<Array<LeaderboardRow>>;
    getLevelById(id: bigint): Promise<CustomLevel | null>;
    getMyLevel(sessionId: string): Promise<CustomLevel | null>;
    getMyLevels(sessionId: string): Promise<Array<CustomLevel>>;
    getMyStats(sessionId: string): Promise<UserStats | null>;
    getMyUsername(sessionId: string): Promise<string | null>;
    getPublicLevels(): Promise<Array<CustomLevel>>;
    getSpeedLeaderboard(): Promise<Array<LeaderboardRow>>;
    registerUsername(sessionId: string, name: string): Promise<void>;
    resetMyUsername(sessionId: string): Promise<void>;
    saveCustomLevel(sessionId: string, name: string, platformsJson: string, worldWidth: bigint, bgHue: bigint): Promise<void>;
    saveGameResult(sessionId: string, stageReached: bigint, deathsThisRun: bigint, completionTimeMs: bigint): Promise<void>;
}
import type { CustomLevel as _CustomLevel, UserStats as _UserStats } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adminResetUsernames(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminResetUsernames(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminResetUsernames(arg0);
            return result;
        }
    }
    async claimOwnerPrincipal(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.claimOwnerPrincipal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimOwnerPrincipal(arg0);
            return result;
        }
    }
    async deleteLevel(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteLevel(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteLevel(arg0, arg1);
            return result;
        }
    }
    async deleteMyLevel(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMyLevel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMyLevel(arg0);
            return result;
        }
    }
    async getAllUsernames(): Promise<Array<[string, string]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsernames();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsernames();
            return result;
        }
    }
    async getLeaderboard(): Promise<Array<LeaderboardRow>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getLevelById(arg0: bigint): Promise<CustomLevel | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLevelById(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLevelById(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyLevel(arg0: string): Promise<CustomLevel | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyLevel(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyLevel(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyLevels(arg0: string): Promise<Array<CustomLevel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyLevels(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyLevels(arg0);
            return result;
        }
    }
    async getMyStats(arg0: string): Promise<UserStats | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyStats(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyStats(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyUsername(arg0: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyUsername(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyUsername(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicLevels(): Promise<Array<CustomLevel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicLevels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicLevels();
            return result;
        }
    }
    async getSpeedLeaderboard(): Promise<Array<LeaderboardRow>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSpeedLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSpeedLeaderboard();
            return result;
        }
    }
    async registerUsername(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUsername(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUsername(arg0, arg1);
            return result;
        }
    }
    async resetMyUsername(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetMyUsername(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetMyUsername(arg0);
            return result;
        }
    }
    async saveCustomLevel(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCustomLevel(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCustomLevel(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async saveGameResult(arg0: string, arg1: bigint, arg2: bigint, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveGameResult(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveGameResult(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomLevel]): CustomLevel | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserStats]): UserStats | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
